### ISSUE TITLE
Write article about: Deploy Laravel, MySql and ElasticSearch to K8s

### ISSUE THREAD

**Issue by keithmifsud** [learnk8s/learnk8s.io#41]
- [ ] Completed all preliminary tasks as per learnk8s/team#45
- [ ] Submitted all changes to this PR #120 
- [ ] Completed all post-publish tasks as per learnk8s/team#45

**Comment by danielepolencic** [comment]
@keithmifsud is this in progress? is there an outline?
If this is at a very early stage, perhaps we could pause it and resume it later on. There're some other topics that we should tackle first.

**Comment by keithmifsud** [comment]
Hmmm...I have an outline and the demo application. I also have drafts of the command snippets but they need major improvement because all I have, I did while learning volumes. Please let me know if I should focus on finishing this fast or if I should focus on something else. I am available fulltime for the next 7 days.

**Comment by danielepolencic** [comment]
I think you should commit everything you have and raise a PR. The PR will stay pending until we address it, but at least we don't waste your work.

**Comment by danielepolencic** [comment]
For future reference: https://medium.com/google-cloud/a-guide-to-deploy-elasticsearch-cluster-on-google-kubernetes-engine-52f67743ee98

**Comment by keithmifsud** [comment]
Thanks! It's still on Grammarly but I'll raise a PR asap.
